# @package _global_

defaults:
  - motion_tracking

# Env structure
env:
  _target_: humanoidverse.envs.motion_tracking.statistics_trackingv1.Tracking
  config:
    max_episode_length_s: 20


# Globally accessible parameters
log_task_name: motion_statistics

eval_overrides:
  env:
    config:
      max_episode_length_s: 100000
